apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  #local:
  #push: false
  artifacts:
    - image: phuchoang2411/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: phuchoang2411/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.ts'
            dest: .
    - image: phuchoang2411/communicate-interface
      context: communicate-interface
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: phuchoang2411/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.ts'
            dest: .
    - image: phuchoang2411/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.ts'
            dest: .
    - image: phuchoang2411/temporary-store
      context: temporary-store
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.ts'
            dest: .
    - image: phuchoang2411/forumauth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
